apiVersion: v1
kind: Pod
metadata:
  name: swashikan-jenkins
spec:
  containers:
  - name: swashikan
    image: 791532114280.dkr.ecr.us-east-1.amazonaws.com/swashikan:lsacone
    resources:
        limits:
          cpu: "500m"
          memory: "12Gi"
        requests:
          cpu: "500m"
          memory: "12Gi"
    workingDir: /home/node/jenkins 
    volumeMounts:
      - mountPath: /home/node/jenkins
        name: swashikan-volume
        readOnly: false
  volumes:
    - name: swashikan-volume
      persistentVolumeClaim:
        claimName: dh-pv
