apiVersion: v1
kind: Pod
metadata:
  name: sch-sit2-jenkins
spec:
  containers:
  - name: sch-code-builder
    image: 791532114280.dkr.ecr.us-east-1.amazonaws.com/lsac-platform:ubuntu_3
    resources:
        limits:
          cpu: "500m"
          memory: "12Gi"
        requests:
          cpu: "500m"
          memory: "12Gi"
    workingDir: /home/node/jenkins 
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: "/home/node/jenkins"
        name: "workspace-volume"
        readOnly: false
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
